### ISSUE TITLE
lesson.md v entry.yml má být bez přípony

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/python-pro-powerbi#1]
V `entry.yml` pokud je další část už soubor s příponou `.md`, tak tu příponu souboru to v tom YAMLu nechce.

https://github.com/pesikj/python-pro-powerbi/blob/a0bb32ec5001ff5f7bfa9b77daef07dfffe6d5d6/power-bi/power-bi/entry.yml#L4

**Comment by pesikj** [comment]
@ZelenyMartin Super, díky.
